### ISSUE TITLE
Edit the Service worker

### ISSUE THREAD

**Issue by nerdeveloper** [CodeClubPh/codeclubph#10]
Hello @alabobriggs 

you are expected to work on the service worker file found in the root dir.

The service worker there use a functionally called *Cache-first network*

There is an array of files there as you may notice

you are to:

1.  Ensure the PWA prompt user to install it.
2. Ensure the PWA updates when there are new contents automatically
3. Ensure the app has a fallback file when it there is no cache available
4. Look through the index.html. Then compare it with the service worker (cache.addAll)  and remove any file in that array that no longer needed for caching. 
4. Submit a PR and Wait for review. 

Good luck!

**Comment by alabobriggs** [comment]
I am having issues running project locally. After running npm install it prompted that run ```npm install gulp``` which I did and I still get an error saying 'no gulpfile found'
![Screenshot from 2019-10-03 16-17-00](https://user-images.githubusercontent.com/38571291/66140020-49d7af00-e5f9-11e9-8c86-d19df0c1820b.png)

**Comment by ogurinkaben** [comment]
> I am having issues running project locally. After running npm install it prompted that run `npm install gulp` which I did and I still get an error saying 'no gulpfile found'
> ![Screenshot from 2019-10-03 16-17-00](https://user-images.githubusercontent.com/38571291/66140020-49d7af00-e5f9-11e9-8c86-d19df0c1820b.png)

Sorry about that.. I was supposed to create a new README file with the actual installation guide for the project.. It doesn't run on gulp anymore, we migrated  to webpack

**Comment by nerdeveloper** [comment]
I am sorry you noticed this, the documentation has not yet been updated. We don't run gulp on this project the fix is at #8.

Thank you!

**Comment by alabobriggs** [comment]
In the task I am to carry out specifically task 2. I am to ensure new contents update automatically. In other to enable this a  _network-strategy_ has to be implemented. Can I go ahead and change the fetch strategy from _cache-first_  to  _network-first_  @nerdeveloper 

Or maybe you need to clarify what you mean by 'ensure new contents update automatically'

**Comment by nerdeveloper** [comment]
YES! you go ahead and change it. I expect to see some notification telling the user to update their app but if it can happen at the background, then cool!

**Comment by nerdeveloper** [comment]
Thank you for this! First Contributor!
