### ISSUE TITLE
Create more logo for more screen sizes

### ISSUE THREAD

**Issue by nerdeveloper** [CodeClubPh/codeclubph#13]
Hello @judexes  you are expected to:

1. Visit this URL  and download the icon : [Icon image](https://github.com/CodeClubPh/codeclubph/blob/master/src/images/assets/pwa/icon512.png)
2. Create a folder inside the src/ folder called *icons*.
3. Create icon sizes for the following screen sizes

- 72x72
- 36x36
- 1024x1024
- 180x180
- 152x152
- 120x120
- 76x76

4. Save each by their size name. eg *76x76.png*, *1024x1024.png*
5. Submit a PR
6. Wait for a review

Good luck!

**Comment by judexes** [comment]
Created the folder 'icons' inside 'src' folder.
Resized and saved the icons by their given file size.

**Comment by judexes** [comment]
What's a PR. 

Thanks.

**Comment by nerdeveloper** [comment]
okay? where is your submitted a PR?

**Comment by judexes** [comment]
Project report?

**Comment by nerdeveloper** [comment]
Pull Request, do you have any idea working with GitHub?

**Comment by judexes** [comment]
[master 6d6a380] Created the folder 'icons' inside 'src' folder. Resized and saved the icons by their given file size..
 7 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 src/icons/1024x1024.png
 create mode 100644 src/icons/120x120.png
 create mode 100644 src/icons/152x152.png
 create mode 100644 src/icons/180x180.png
 create mode 100644 src/icons/36x36.png
 create mode 100644 src/icons/72x72.png
 create mode 100644 src/icons/76x76.png


But the created folder won't show up in the src folder
[https://github.com/CodeClubPh/codeclubph/tree/master/src](url)

**Comment by nerdeveloper** [comment]
Did you fork the repo or create a branch?

**Comment by judexes** [comment]
It is my first time working on a collaborative project.

**Comment by judexes** [comment]
I push to git directly

**Comment by nerdeveloper** [comment]
YES! you are supposed to use git. hello @cyiboy you two should work together. Try assisting him on how to fork the repo or create a branch and submit a PR.

I'd love to see what you two can come up with.

**Comment by judexes** [comment]
Okay. Thanks.

**Comment by nerdeveloper** [comment]
The mean time @judexes read up to https://css-tricks.com/how-to-contribute-to-an-open-source-project it will help you get up to speed

**Comment by nerdeveloper** [comment]
Hello @miracleonyenma Please can you help out with this. I will be grateful for that

**Comment by miracleonyenma** [comment]
Okay
Let's what I can do

**Comment by nerdeveloper** [comment]
@miracleonyenma Thank you so much for doing this!. you have been an amazing person
