### ISSUE TITLE
CSS files not linked properly on local server

### ISSUE THREAD

**Issue by alabobriggs** [CodeClubPh/codeclubph#19]
The css are not linked properly on the dev server. What is on the html files are `src/dist/<css name goes here>` but what is correct for dev is `src/css/<css name goes here`. Using the current version a broke screen is shown on the app.

below is the html code that is giving an error

```
...
    <link rel="stylesheet" href="src/dist/custom.css">
...
```

which can be solved locally by changing to

```
<link rel="stylesheet" href="src/css/responsive.css">
```

**image on browser**
![Screenshot from 2019-12-24 06-35-37](https://user-images.githubusercontent.com/38571291/71395813-e10c3b80-2617-11ea-95fc-e0484caefc3c.png)

**Comment by ogurinkaben** [comment]
This issue has been fixed, try cloning the latest version of the app
