### ISSUE TITLE
Create logo for different shape and sizes 

### ISSUE THREAD

**Issue by nerdeveloper** [CodeClubPh/codeclubph#6]
Hello, you are expected to:

1. Visit this URL  and download the icon : [Icon image](https://github.com/CodeClubPh/codeclubph/blob/master/src/images/assets/pwa/icon512.png)
2. Create a folder inside the src/ folder called *icons*.
3. Create icon sizes for the following screen sizes

- 44x44
- 48x48
- 1240x600
- 300x300
- 150x150
- 88x88

4. Save each by their size name. eg *44x44.png*, *88x88.png*
5. Submit a PR
6. Wait for a review

Good luck

**Comment by miracleonyenma** [comment]
* Icon

**Comment by miracleonyenma** [comment]
* Icon size 1240x600 
Is that a typo?

**Comment by nerdeveloper** [comment]
No, it's not.

Please use this link to generate the icons: https://github.com/CodeClubPh/codeclubph/blob/master/src/images/assets/pwa/icon512.png

**Comment by miracleonyenma** [comment]
okay

**Comment by nerdeveloper** [comment]
Thank you so miracle @miracleonyenma you are an awesome person.
