### ISSUE TITLE
create logo for difference screen size

### ISSUE THREAD

**Issue by nerdeveloper** [CodeClubPh/codeclubph#7]
Hello, you are expected to:

1. Visit this URL  and download the icon : [Icon image](https://github.com/CodeClubPh/codeclubph/blob/master/src/images/assets/pwa/icon512.png)
2. Create a folder inside the src/ folder called *icons*.
3. Create icon sizes for the following screen sizes

- 24x24
- 50x50
- 620x300
- 192x192
- 144x144
- 96x96

4. Save each by their size name. eg *44x44.png*, *88x88.png*
5. Submit a PR
6. Wait for a review

Good luck

**Comment by kovsk1** [comment]
Hi, can I pick up this issue?

**Comment by nerdeveloper** [comment]
of course, you can!. I will be glad. Can I add you to the team working on this project @CodeClubPh/pwa-serverless-team

**Comment by kovsk1** [comment]
Yes, of course

**Comment by nerdeveloper** [comment]
Please @cryolis accept your invitation

**Comment by nerdeveloper** [comment]
I am closing this now because you have done an amazing job. Thank you.
