### ISSUE TITLE
Migrating to Zeit Now Sever-less Platform

### ISSUE THREAD

**Issue by nerdeveloper** [CodeClubPh/codeclubph#8]
Hello @phirmware 

You are to migrate the site to Zeit now Serverless and build a CI to do this

1. You will use Travis CI for your CI.
2. Ensure every merged commit(only in the master is pushed automatically)
3.  Integrate Zeit with your CI for continuous deployment.
4. Share a  working link 
4. Submit a PR and wait for a review 

Good luck!

**Comment by phirmware** [comment]
I did the following steps found on the readMe

Cloned the project from github.
Ran npm i
Ran npm run dev
Result - When i run npm run dev the app doesnt run
![Screenshot 2019-10-02 13:26:06](https://user-images.githubusercontent.com/32414323/66108446-82a46380-e5ba-11e9-8a96-55dff256a353.png)

**Comment by nerdeveloper** [comment]
Kindly note that we don't run gulp. we use webpack to run the bundlers and parsers.
 Follow these steps: 

- npm i 
- npm i -g webpack@3.4.1
- npm run watch
- Install *Live server* extension 
<img width="729" alt="Screenshot 2019-10-03 at 09 18 05" src="https://user-images.githubusercontent.com/26016664/66110587-02ccc800-e5bf-11e9-928d-942378179947.png">
- Click on *Go Live*
<img width="227" alt="Screenshot 2019-10-03 at 09 21 30" src="https://user-images.githubusercontent.com/26016664/66110689-3576c080-e5bf-11e9-96f6-91926e0c6690.png">
It should fire up.

the README will update soon. Please, @simplytammy we need a fix.

**Comment by alabobriggs** [comment]
I suggest the ```dev script``` in the package.json file be updated too

**Comment by nerdeveloper** [comment]
> I suggest the `dev script` in the package.json file be updated too

@simplytammy see how we can make the project's documentation updated soon

**Comment by ogurinkaben** [comment]
> > I suggest the `dev script` in the package.json file be updated too
> 
> @simplytammy see how we can make the project updated soon

Copy that !!

**Comment by judexes** [comment]
Received.

With regard.

**Comment by nerdeveloper** [comment]
Thank you very much, o ye bush baby @phirmware
