### ISSUE TITLE
App doesnt run after npm i and mpn run local

### ISSUE THREAD

**Issue by phirmware** [CodeClubPh/codeclubph#9]
I did the following steps found on the readMe
1. Cloned the project from github.
2. Ran npm i 
3. Ran npm run dev
Result - When i run `npm run dev` the app doesnt run
![Screenshot 2019-10-02 13:26:06](https://user-images.githubusercontent.com/32414323/66043967-6ea82580-e518-11e9-94fc-a2d6d32a8ded.png)

**Comment by nerdeveloper** [comment]
Hello @phirmware, 

You were not supposed to create an issue here. 

Your issues are to be placed in  issue #8 

Thank you.
